import base64
import hashlib
import json
import os
from typing import Iterable, List
from urllib import request

from workers.common.job_client import JobClient
from workers.common.queue_runner import QueueRunner, poll_forever
from workers.common.structured_logging import WorkerLogger


def build_data_yaml(names: Iterable[str]) -> str:
    ordered = list(names)
    return "train: images/train\nval: images/val\nnames:\n  - " + "\n  - ".join(ordered) + "\n"


def build_package_tree(workdir: str, names: List[str]) -> None:
    os.makedirs(os.path.join(workdir, "images"), exist_ok=True)
    os.makedirs(os.path.join(workdir, "labels"), exist_ok=True)
    with open(os.path.join(workdir, "data.yaml"), "w", encoding="utf-8") as f:
        f.write(build_data_yaml(names))
    with open(os.path.join(workdir, "labels", "0001.txt"), "w", encoding="utf-8") as f:
        f.write("0 0.5 0.5 0.2 0.2\n")
    with open(os.path.join(workdir, "images", "README.txt"), "w", encoding="utf-8") as f:
        f.write("generated by packager worker\n")


def build_bundle_entries(workdir: str) -> List[dict]:
    entries: List[dict] = []
    for root, _, files in os.walk(workdir):
        for name in sorted(files):
            abs_path = os.path.join(root, name)
            rel_path = os.path.relpath(abs_path, workdir).replace(os.sep, "/")
            with open(abs_path, "rb") as f:
                body = f.read()
            entries.append(
                {
                    "path": rel_path,
                    "body": base64.b64encode(body).decode("ascii"),
                    "checksum": hashlib.sha256(body).hexdigest(),
                }
            )
    return entries


def complete_artifact(artifact_id: int, entries: List[dict], base_url: str, opener=None):
    payload = json.dumps({"entries": entries}).encode("utf-8")
    req = request.Request(
        url=base_url.rstrip("/") + f"/internal/artifacts/{artifact_id}/complete",
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with (opener or request.urlopen)(req):
        return None


def run_package_job(job: dict, base_url: str | None = None, opener=None):
    payload = job.get("payload", {})
    workdir = payload.get("workdir", os.path.join("/tmp", f"packager-{job['job_id']}"))
    names = payload.get("names", ["person"])
    build_package_tree(workdir, names)
    entries = build_bundle_entries(workdir)
    artifact_id = payload.get("artifact_id")
    if artifact_id:
        complete_artifact(artifact_id, entries, base_url or os.getenv("API_BASE_URL", "http://127.0.0.1:8080"), opener=opener)
    result = {
        "status": "succeeded",
        "total_items": len(entries),
        "succeeded_items": len(entries),
        "failed_items": 0,
        "workdir": workdir,
        "events": [
            {
                "event_level": "info",
                "event_type": "progress",
                "message": "worker progress",
                "detail_json": {
                    "total_items": len(entries),
                    "succeeded_items": len(entries),
                    "failed_items": 0,
                },
            }
        ],
    }
    if artifact_id:
        result["result_ref"] = {
            "result_type": "artifacts",
            "result_count": 1,
            "artifact_ids": [artifact_id],
        }
    return result


def build_packager_runner(worker_id: str | None = None):
    return QueueRunner(
        worker_id=worker_id or os.getenv("WORKER_ID", "packager-local"),
        accepted_job_types={"artifact-package"},
        resource_lane="jobs:cpu",
        capabilities={"artifact_packaging"},
    )


def main():
    runner = build_packager_runner()
    client = JobClient(base_url=os.getenv("API_BASE_URL", "http://127.0.0.1:8080"))
    logger = WorkerLogger(component="packager_worker")
    poll_forever(redis_addr=os.getenv("REDIS_ADDR", "localhost:6379"), lane="jobs:cpu", runner=runner, handler=run_package_job, job_client=client, logger=logger)


if __name__ == "__main__":
    main()
